🔀 :: (#3) 첨부파일 엔티티 생성
team-xquare/v1-service-attachment pull request #4
Opened 2022-11-21 06:11 UTC by lyutvs

close #3

2022-11-21 06:22 UTC, jhhong0509 requested changes

2022-11-21 06:22 UTC, jhhong0509 commented on buildSrc/src/main/kotlin/Dependencies.kt
> +    const val UUID_TIME = "com.fasterxml.uuid:java-uuid-generator:${DependencyVersions.UUID_TIME_VERSION}"
원래 UUID가 Timestamp 기반 생성인걸로 아는데 이걸 쓰면 뭐가 바뀌는겨?

2022-11-21 06:22 UTC, jhhong0509 commented on src/main/kotlin/com/xquare/v1serviceattachment/domain/entity/FeedAttachment.kt
> +    val feedId: UUID,
p1) 이 첨부파일 서버를 피드에서만 사용하는건 아니라서 이거는 빼야될듯

2022-11-21 06:22 UTC, jhhong0509 commented on src/main/kotlin/com/xquare/v1serviceattachment/domain/entity/FeedAttachment.kt
> +    val fileName: String
p2) fileName도 있으면 좋긴 할텐데 filePath도 필요하지 않음?
사용되는 s3 버킷이 바뀔수도 있는거라 fullPath 다 저장 가능하게 VARCHAR 사이즈 크게 해놓으면 될듯?

2022-11-21 06:22 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2022-11-21 06:24 UTC, lyutvs commented on buildSrc/src/main/kotlin/Dependencies.kt
> +    const val UUID_TIME = "com.fasterxml.uuid:java-uuid-generator:${DependencyVersions.UUID_TIME_VERSION}"
저 의존성을 사용하지 않으면 시간 기반 난수 생성이 안되는 걸로 알고 있어서 추가 했습니다

2022-11-21 06:24 UTC, lyutvs commented on src/main/kotlin/com/xquare/v1serviceattachment/domain/entity/FeedAttachment.kt
> +    val feedId: UUID,
이부분은 erd를 바꿔야 할것 같아요

2022-11-21 06:25 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2022-11-21 06:25 UTC, lyutvs commented on src/main/kotlin/com/xquare/v1serviceattachment/domain/entity/FeedAttachment.kt
> +    val fileName: String
erd랑 함께 수정 할게요

2022-11-21 07:46 UTC, jhhong0509 commented on buildSrc/src/main/kotlin/Dependencies.kt
> +    const val UUID_TIME = "com.fasterxml.uuid:java-uuid-generator:${DependencyVersions.UUID_TIME_VERSION}"
ㅇㅎ v4는 완전 난수 기반이구나 틀딱이라 ㅎ
쨋든 뭐 PK Indexing 속도때문에 이걸로 한거임?

2022-11-21 07:53 UTC, lyutvs commented on buildSrc/src/main/kotlin/Dependencies.kt
> +    const val UUID_TIME = "com.fasterxml.uuid:java-uuid-generator:${DependencyVersions.UUID_TIME_VERSION}"
데이터가 많아지면 많아질수록 시간 정렬한 UUID가 빨라서 이걸로 했어요

2022-11-21 07:58 UTC, jhhong0509 commented on buildSrc/src/main/kotlin/Dependencies.kt
> +    const val UUID_TIME = "com.fasterxml.uuid:java-uuid-generator:${DependencyVersions.UUID_TIME_VERSION}"
UUID v1은 보안 취약성이 있는걸로 아는데 ㄱㅊ?

2022-11-21 07:59 UTC, jhhong0509 commented on buildSrc/src/main/kotlin/Dependencies.kt
> +    const val UUID_TIME = "com.fasterxml.uuid:java-uuid-generator:${DependencyVersions.UUID_TIME_VERSION}"
UUID v6는 어떰?

2022-11-21 09:55 UTC, lyutvs commented on buildSrc/src/main/kotlin/Dependencies.kt
> +    const val UUID_TIME = "com.fasterxml.uuid:java-uuid-generator:${DependencyVersions.UUID_TIME_VERSION}"
지금 서버 운영체제가 unix 기반 이니까 v6보다 비트수가 작은 v7은 어떤가요??

2022-11-21 10:01 UTC, lyutvs commented on buildSrc/src/main/kotlin/Dependencies.kt
> +    const val UUID_TIME = "com.fasterxml.uuid:java-uuid-generator:${DependencyVersions.UUID_TIME_VERSION}"
아 다시 보니까 작은게 아니었네요 근데 v6보다 v7을 더 많이 사용 하는것 같은데 어떤가요

2022-11-21 10:13 UTC, jhhong0509 commented on buildSrc/src/main/kotlin/Dependencies.kt
> +    const val UUID_TIME = "com.fasterxml.uuid:java-uuid-generator:${DependencyVersions.UUID_TIME_VERSION}"
많이 사용하는게 중요한게 아니라 어떤 차이점이 있는지를 봐야지
사실 내 기준에선 v1의 보안 이슈만 해결되었다면 별 상관 없음 v4든 v7이든 사실 스퀘어 정도 규모에서 성능 저하를 체감할정도는 아니라서
단지 v6이든 v7이든 선택할거면 선택한 이유를 말할 수 있게 여기에 적든 노션에 적든 다른 애들들을 설득할 수 있을만한 문서를 적어보셈

2022-11-21 13:35 UTC, lyutvs commented on buildSrc/src/main/kotlin/Dependencies.kt
> +    const val UUID_TIME = "com.fasterxml.uuid:java-uuid-generator:${DependencyVersions.UUID_TIME_VERSION}"
일단 v6와 v7은 시간단위가 다른데 v6가 나노초로 v7보다 더 단위가 크고, v4를 사용 하는것과 TimeStamp기반 UUID를 사용할때 query속도를 봤을때 월등히 TimeStamp가 높아 timestamp를 지원 하고 v7보다 더 큰 시간 단위인 나노초로 보안성와 그레고리력을 사용 하는 v6를 선택하는것이 추후 상황을 고려 했을때 적절하다 판단됩니다.

2022-11-21 14:08 UTC, lyutvs commented
<img width="674" alt="스크린샷 2022-11-21 오후 11 08 29" src="https://user-images.githubusercontent.com/80021665/203075403-ba79fb29-9fb9-42e3-9098-4bd6b0eb71cf.png">
erd 첨부아이디 부분 이름이 약간 고민좀 해봐야할것 같은데 좀더 좋은게 뭐가 있을까요?

2022-11-21 14:29 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2022-11-21 14:40 UTC, eogus2513 commented
> <img alt="스크린샷 2022-11-21 오후 11 08 29" width="674" src="https://user-images.githubusercontent.com/80021665/203075403-ba79fb29-9fb9-42e3-9098-4bd6b0eb71cf.png">
> 
> erd 첨부아이디 부분 이름이 약간 고민좀 해봐야할것 같은데 좀더 좋은게 뭐가 있을까요?

여기서 아이디가 순서인데 그건 뭘 나타내는 거야?

2022-11-21 23:48 UTC, lyutvs commented
> 여기서 아이디가 순서인데 그건 뭘 나타내는 거야?

어 그러네 저건 뭐지 내가 안만들어서 모름

2022-11-22 01:39 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2022-11-22 01:41 UTC, jhhong0509 commented on buildSrc/src/main/kotlin/Dependencies.kt
> +    const val UUID_TIME = "com.fasterxml.uuid:java-uuid-generator:${DependencyVersions.UUID_TIME_VERSION}"
그럼 v6이 v7보다 좋은걸로만 보이는데, v7에서 개선된 점은 어떤게 있음?
나노초가 장점이 되기에는 별로 필요한건 아님 나노초가 장점이 되는 상황은 '1ms 안에 엄청나게 많은 요청을 처리할 때 UUID 중복 예방'일텐데, 굳이 그럴 필요가 있음?
다른 장점으로 고민해봐 'v6가 더 좋다'라는 생각에 매몰되지 말고
그리고 그보다 상위 버전이나 하위 버전은? 걔네들도 고려 대상에 넣고, 스퀘어에서는 전부 UUID 아닌데 따로 개인 프로젝트 할 땐 UUID 외에 PK 타입도 고려해볼만함
복잡해서 추천하진 않겠지만 서비스 내부간의 통신에선 Auto Increment를 PK로 쓰되, 외부에 노출할 땐 Unique Index가 걸려있는 uuid를 쓴다던가 다른 방법도 고려할 수 있음

2022-11-23 14:18 UTC, lyutvs commented on buildSrc/src/main/kotlin/Dependencies.kt
> +    const val UUID_TIME = "com.fasterxml.uuid:java-uuid-generator:${DependencyVersions.UUID_TIME_VERSION}"
uuid 에는 1~5의 공식 버전이 있고 개발자가 좀더 편하게 UUID를 사용할수 있도록 6 ~ 8 까지의 버전이 있습니다.  그중 v1은 현재 시각을 기반으로 uuid값을 생성하는데 uuid가 생성된 시각과 MAC주소로 uuid를 유추할 수 있기 때문에 안전하지 않습니다. 그래서 저희는 v1을 개선한 버전인 v4를 고려해봐야 합니다. v4는 무작위로 생성된 UUID를 가집니다. 중복률은 운석이 떨어질정도의 확률로 중복될 확률은 매우 낮습니다. 저희는 거기서 한단계 더 좋은 성능을 내기 위해 현재 타임스탬프를 사용해 UUID를 사용하는것을 고려해볼필요가 있습니다. 타임스탬프를 사용할시 두가지 장점을 가져올수 있습니다. 1. UUID별로 정렬하면 생성된 순서대로 표시됩니다. 2. 정렬된 UUID는 무작위 UUID에 비해 인데스 데이터베이스 열에 더 효율적으로 저장합니다. 또한 쿼리 속도를 높힐수 있습니다. 타임스탬프를 사용하지 않을 경우와 사용한 경우, AI(Auto Increment) 3가지 상황을 비교했을경우 데이터양이 많아지면 많아질수록 타임스탬프를 사용하여 DB를 설계하면 쿼리 속도가 증가하는걸 볼수 있었습니다.  기존의 5개의 버전은 RFC 4122를 설명 합니다. 하지만 RFC를 정의 하는 3가지 속성에 부합하는 버전은 없습니다. 
#### 3가지 속성
`1. 원시 바이트를 기준으로 정렬하면 포함된 타임스탬프를 기준으로 정렬하는 것과 동일한 시퀀스가 생성`
`2. 추출가능`
`3. 전역 고유성`
주요 문제는 시간 필드의 바이트 시퀸스로 인해 기존 버전으로는 첫번째 요구사항을 충족할 수 없습니다.

그래서 v6~8을 고려하는 것 입니다. v6는 높은 바이트에서 낮은바이트로 인코딩돤 날짜를 가지고 있어 불투명한 바이트 묶음으로 취급될 때 시간별로 올바르게 정렬됨니다. v6는 v1버전으로생기는 인접성 개선을 위해 생겨났습니다. 기존 UUID를 사용하는 경우 UUID v6를 사용해야 하지만 UUID v1을 사용하지 않는 경우 v7을 고려 해보는것이 좋다 생각 합니다.

v7은 널리 알려진 Unix epoch 타임스탬프 송신원으로부터 파생된 타임 오더치 필드를 사용 합니다. 밀리초를 사용 하며 v1,v6의 엔트로피 특성이 개선되었습니다. 또한 1초 미만의 임의의 정밀도로 부호화하여 사용합니다. v7에서 제공되는 주요 장점으로 한시스템에 의해 생성된 UUID는 다른 시스템에 의해 해석되는 생성기 또는 파서의 하위 섹션 정밀도중 더 낮은 값을 보장합니다. 낮은 정밀도를 보장하면 생기는 이점으론 UUID값을 해석할 때 시스템은 올바르게 기능하기 위해 부호화 중에 사용된 정밀도를 인식할 필요가 없어 낮은 정밀도로 나오는 장점으로 꼽을수 있습니다. **그때문에 저는 다른 버전보다 v7을 사용여 DB를 구성할 경우 RFC의 3가지 속성에 부합 하면서 v1과 v6의 엔트로피 특성을 개선하며 낮은 정밀도를 사용하는 것을 고려하여 보는것이 좋다 생각 합니다.**

2022-11-23 14:20 UTC, lyutvs commented on buildSrc/src/main/kotlin/Dependencies.kt
> +    const val UUID_TIME = "com.fasterxml.uuid:java-uuid-generator:${DependencyVersions.UUID_TIME_VERSION}"
사용한 자료는
* http://gh.peabody.io/uuidv6/
* https://www.sohamkamani.com/uuid-versions-explained/
* https://www.uuidtools.com/uuid-versions-explained
* https://www.ietf.org/archive/id/draft-peabody-dispatch-new-uuid-format-01.html#name-uuidv6-timestamp-usage
* https://www.ietf.org/archive/id/draft-peabody-dispatch-new-uuid-format-04.html#name-uuid-version-

를 보며 이해 했습니다.

2022-11-24 00:08 UTC, jhhong0509 commented on buildSrc/src/main/kotlin/Dependencies.kt
> +    const val UUID_TIME = "com.fasterxml.uuid:java-uuid-generator:${DependencyVersions.UUID_TIME_VERSION}"
정리 잘했네 굿
사실 UUID 정하는데 이렇게까지 할 필요는 없지만 그래도 뭔가 적용하려면 다른 사람들 설득이 우선이라 연습해두면 좋음

2022-11-24 00:09 UTC, jhhong0509 commented on buildSrc/src/main/kotlin/Dependencies.kt
> +    const val UUID_TIME = "com.fasterxml.uuid:java-uuid-generator:${DependencyVersions.UUID_TIME_VERSION}"
그럼 UUID v7로 하는거지? 다른 애들들도 읽어보고 결정하셈

2022-11-24 00:10 UTC, lyutvs commented on buildSrc/src/main/kotlin/Dependencies.kt
> +    const val UUID_TIME = "com.fasterxml.uuid:java-uuid-generator:${DependencyVersions.UUID_TIME_VERSION}"
넵!

2022-11-24 02:53 UTC, xquare-admin commented
P1: 꼭 반영해주세요 (Request changes)
          P2: 적극적으로 고려해주세요 (Request changes)
          P3: 웬만하면 반영해 주세요 (Comment)
          P4: 반영해도 좋고 넘어가도 좋습니다 (Approve)
          P5: 그냥 사소한 의견입니다 (Approve)
          질문은 그냥 코멘트로 😃

2022-11-29 13:35 UTC, lyutvs commented
비로 컷

2022-11-29 13:35 UTC, closed without merging